BURY_LOW_PRIORITY = true
CLOSE_TO_TRAY = true
COMPACT_ROOT_SPACES = false
DUAL_MENTION_UNREAD_COUNTS = true
FRAME_DROP_SPINNER = false
HIDE_AUTHENTICITY_NOT_GUARANTEED = false
INITIAL_WINDOW_HEIGHT = 900
INITIAL_WINDOW_WIDTH = 1200
PIN_FAVORITES = true
PSEUDO_SPACE_ACCOUNTS = false
PSEUDO_SPACE_GROUPS = false
PSEUDO_SPACE_NOTIFICATIONS = true
PSEUDO_SPACE_SPACELESS = true
PSEUDO_SPACE_SPACELESS_GROUPS = false
PSEUDO_SPACE_UNREAD = false
RENDER_AVATAR_STATES = true
SHOW_DEV_INFOS = true
SORT_BY_UNREAD = false
THEME_DARK = true
THEME_FOLLOW_SYSTEM = false
URL_PREVIEWS = true
VIEW_HIDDEN_EVENTS = true
VIEW_REDACTIONS = true
